/*= ProjectConfiguration[LAYER].h is autogenerated. Do not Modify =*/

#ifndef ProjectConfigurationAutomatID_DEMO_IOS_h
#define ProjectConfigurationAutomatID_DEMO_IOS_h

	#undef MULTIPUNTAMENTO
	#define AUTOMATID_LICENSE @"sci-demoapp-prod-ios"

#endif /* ProjectConfigurationAutomatID_DEMO_IOS_h*/