/*= ProjectConfiguration.h is autogenerated. Do not Modify =*/

#ifndef ProjectConfigurationAutomatID_DEMO_IOS_h
#define ProjectConfigurationAutomatID_DEMO_IOS_h

	#define MULTIPUNTAMENTO
	#define OMVLICENSE @"sci-demoapp-multi-ios"

#endif /* ProjectConfigurationAutomatID_DEMO_IOS_h*/